### ISSUE TITLE
Initiating AvnApi with the key as a parameter

### ISSUE THREAD

**Issue by gilles-hemmerle** [Aventus-Network-Services/avn-api#1]
Currently, if we want to generate multiple wallets and chose one to be used for the next commands it seems that we have to change the current wallet with something like `process.env.SURI = "PRIVATE_KEY";`.

Wouldn't it be better to allow `api.init();` to take the private key as a parameter instead of using a global environment variable ?

**Comment by fluorostani** [comment]
Hey Gilles, thanks for the suggestion, it's been implemented and will be part of the next release
