### ISSUE TITLE
Missing argument in documentation

### ISSUE THREAD

**Issue by pazuro** [Aventus-Network-Services/avn-api#45]
Some examples are missing the avn gateway url as an argument in the avn api constructor.

Maybe the examples could read more like the following:
 ```
 import { AvnApi, SetupMode } from 'avn-api';

// The AvN gateway endpoint:
const AVN_GATEWAY_URL = 'https://...';

 const singleUserSdk = new AvnApi(AVN_GATEWAY_URL, { setupMode : SetupMode.SingleUser } ) // OR
 const multiUserSdk = new AvnApi(AVN_GATEWAY_URL, { setupMode : SetupMode.MultiUser } )

 ```

This is also echoed in the usage page of the docs: https://docs.gateway.aventus.io/docs/set_up/usage

**Comment by dr-ngubo** [comment]
@pazuro Thank you for your suggestion. We've added it in the docs https://docs.gateway.aventus.io/docs/set_up/usage
