### ISSUE TITLE
RPCs not compliant with the JSON-RPC spec

### ISSUE THREAD

**Issue by josepot** [Aventus-Network-Services/avn-api#58]
Dear Aventus Team,

I hope this message finds you well. My name is Josep, and I'm the technical lead of the [Polkadot-API (PAPI)](https://papi.how/) team.

In case you're not familiar with Polkadot-API, it's a modern library designed to replace PolkadotJS, built on top of a properly specified and [standardized JSON-RPC API](https://paritytech.github.io/json-rpc-interface-spec/api/chainHead.html) for Polkadot-based networks. The modern JSON-RPC APIs offer many advantages over the legacy ones; you can read more about it [here](https://paritytech.github.io/json-rpc-interface-spec/objectives.html) and [here](https://forum.polkadot.network/t/new-json-rpc-api-mega-q-a/3048#why-do-we-need-a-new-json-rpc-api-9).

We've noticed that there are no available public Aventus RPCs that expose the modern JSON-RPC API. At least, the only one that we are aware of (`wss://public-rpc.mainnet.aventus.network`) doesn't expose it. Also, I wasn't able to test if your chain works using the light-client provider, because I [couldn't find the chainspecs](https://github.com/Aventus-Network-Services/avn-api/issues/57) anywhere 😞.

Our team has developed a [middleware solution](https://papi.how/requirements#polkadot-sdk-110--x--1110) to ensure that Polkadot-API can function seamlessly with chains running older versions of the Polkadot-SDK node. Unfortunately, it appears that the RPC providers for Aventus are using an even older version, which the middleware does not support.

We kindly request that you consider working with your RPC providers to upgrade the PolkadotSDK node to a more modern version that supports the new JSON-RPC API. This upgrade would enable DApp developers to easily interact with your chain using PAPI, unlocking benefits such as improved performance, reduced resource usage, out-of-the-box strong type generation for your chain, and the ability for developers to handle runtime upgrades on the fly.

Thank you for your time and consideration.

Best regards,

Josep

**Comment by nahuseyoum** [comment]
Hi @josepot thank you for reporting this issue. We have since upgraded our node to v1.1 of PolkadotSDK. We are also working on upgrading to 1.16.

**Comment by josepot** [comment]
> Hi @josepot thank you for reporting this issue. We have since upgraded our node to v1.1 of PolkadotSDK. We are also working on upgrading to 1.16.

Thanks for letting me know that! However, it seems that [the RPC provider hasn't been upgraded yet](https://github.com/polkadot-api/compliant-RPCs/blob/main/results/polkadot.txt#L93)? 🤔

**Comment by thadouk** [comment]
Hi @josepot!

We’ve just pushed a new version that addresses the RPC provider issue and is now fully compatible with the Polkadot API. Please give it a try, and let us know if you encounter any further issues!

**Comment by josepot** [comment]
> Hi @josepot!
> 
> We’ve just pushed a new version that addresses the RPC provider issue and is now fully compatible with the Polkadot API. Please give it a try, and let us know if you encounter any further issues.

Nice! Yep, it's [green now](https://github.com/polkadot-api/compliant-RPCs/blob/ed070968a78f60b367903a9665f3275d5f901541/results/polkadot.txt#L93) 🎉.

I will be adding Aventus into the supported list of chains of the [PAPI dev console](https://dev.papi.how/) chains in the next few hours.

If you could please also provide us with a list of valid bootnodes, then we will also add support for connecting to Aventus via the light-client.

Thanks!
